const mongoose = require("mongoose");

const userCarSchema = new mongoose.Schema({
  name: { type: String },
  lastName: { type: String },
  email: { type: String },
  password: [{ type: String, required: true }],
  role: { type: String },
  rut: { type: String },
  logged: { type: String, required: false },
  imgUrl: { type: String, required: false },
  from: { type: String, required: false },
  phone: { type: String, required: false },
  discipline: { type: String, required: false },
  especiality: { type: String, required: false },
  modules: {
    type: [String],
    required: false,
    default: ["baseVM"],
    enum: [
      "baseVM",
      "hrvBasico",
      "hrvAvanzado",
      "cargaInternaMF",
      "entrenamientoBandaBasico",
      "entrenamientoBandaAvanzado",
      "Hub",
      "vmClassEscuelas",
      "vmClassDeportivo",
      "medicionesFisicas",
      "reporteriaBasico",
      "reporteriaAvanzado",
      "controlAsistencia",
      "adminComplejos",
      "facturacionCaja",
      "facturacionPagos",
      "facturacionMensualidad",
      "scoutingBasico",
      "scoutingAvanzado",
      "ligas",
      "agendamientosBasico",
      "agendamientosAvanzado",
      "eventos",
      "cuestionarios",
      "encuestas",
      "controlDeAcceso",
    ],
  },
});

module.exports = mongoose.model("userCar", userCarSchema, "userCar");
